### ISSUE TITLE
Outline Error

### ISSUE THREAD

**Issue by nilababaei** [nilababaei/animal-rescue-website#1]
@hellachella 
My Markbot is telling me that my outline for my main:focus is not working on my adopt.html page.

My CSS:
main:focus {
  outline: 3px solid #000;
}

It works when I try the focus states on my browser, so I don't understand the message. The outline also does work on all my other pages main elements.

<img width="519" alt="screen shot 2018-12-06 at 9 09 31 am" src="https://user-images.githubusercontent.com/31959337/49589162-aa914f00-f936-11e8-8cfc-eb7925d54afb.png">

**Comment by hellachella** [comment]
Can you double check that your modulifier has accessibility selected? I opened it and it has 
```
a:hover, a:focus {
outline: none;
}

```

**Comment by nilababaei** [comment]
I checked and also re-inserted modulifier to make sure it had the accessibility settings turned on but markbot is still telling me my outline isn't working. I also tried adding the outline to that same class in my CSS but it's still not going through.

________________________________

**Comment by hellachella** [comment]
It is totally going through on my end (except performance) . Have you recently committed? Maybe I have cloned an older version?

**Comment by nilababaei** [comment]
I have committed every change up to the present. It goes through completely on my end and even passes performance, but the only thing not letting it pass is the outline error. I tried fumbling around with adding outline and changing it in the css as well but it's not having any results.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hellachella** [comment]
Ok solved.

You don't have any links at all inside of your main div on the adopt page. Markbot is looking for one. 

Add some links, even a fake link. maybe to the levels?

**Comment by hellachella** [comment]
```
<p class="killi push-0">Everything in other <a href="#">levels</a> PLUS: A sign on your sponsored animal's home enclosure with your name as sponsor. Protector status sponsorships have exclusive sponsorship rights to that animal for that year. Protector level sponsors may come for one private tour with a guest. Additional guests can be added to the tour for $50.00 each.</p>
```

For example

**Comment by nilababaei** [comment]
It worked! Thank you so much:))

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
